### ISSUE TITLE
dec!() procedural macro doesn't work on rust stable (1.30.0)

### ISSUE THREAD

**Issue by zazabe** [paupino/rust-decimal#151]
It seems that `dec!()` is not working on the latest rust release.

```rust
extern crate rust_decimal;
extern crate rust_decimal_macros;
use rust_decimal_macros::*;
fn main() {
    let num = dec!(3.14);
}
```
produces this error:
```
error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)
 --> examples/decimal.rs:5:15
  |
5 |     let num = dec!(3.14);
  |               ^^^^^^^^^^

error: aborting due to previous error
```

- rustc 1.30.0 (da5f414c2 2018-10-24)
- rust_decimal = "0.10.2"
- rust_decimal_macros = "0.10.2"

Btw, I tried with `#![feature(proc_macro)]` with no luck...

Am i missing something?

**Comment by paupino** [comment]
I jumped the gun a bit putting this in stable (i.e. my tests still use the `proc_macro_hygiene` feature).
This looks like a [known blog issue](https://github.com/rust-lang/blog.rust-lang.org/issues/285) - it also doesn't look like it will be stabalized for the initial release of Rust 2018. It _does_ work on nightly, however only if you also define `#![feature(proc_macro_hygiene)]`.

I may take a look at the proposed [alternative solution](https://github.com/dtolnay/proc-macro-hack) to see if I can get that working on stable however for the meantime you could feasibly use [this macro definition](https://github.com/paupino/rust-decimal/issues/11#issuecomment-411932922) as a workaround.
